name: Deploy template and docs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build jsPsych experiment
        run: pnpm build
        env:
          VITE_BASE: /${{ github.event.repository.name }}/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare artifact
        run: |
          mkdir -p artifact
          cp -r dist/* artifact/
          cp -r docs artifact/docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./artifact"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
